require("prototypes.inputs")
require("prototypes.selectiontools")
require("prototypes.shortcuts")
require("prototypes.signals")
require("prototypes.speechbubbles")
require("prototypes.sprites")
require("prototypes.styles")
require('prototypes.styles_speechbubbles')